### ISSUE TITLE
GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: Action io.elementary.switchboard.useraccounts.administration is not registered

### ISSUE THREAD

**Issue by LinArcX** [elementary/switchboard-plug-useraccounts#138]
Hi. I've created a [package](https://github.com/void-linux/void-packages/pull/20617) for void-linux. But when i run switchboard, i'll get these error:
https://gist.github.com/LinArcX/5aeff0348a231c8eb5361bf55335a980

**Comment by tintou** [comment]
It means that you don't have the policy file installed https://github.com/elementary/switchboard-plug-useraccounts/blob/master/data/meson.build#L12 that's probably something to do with your package

**Comment by LinArcX** [comment]
@tintou Actually i've installed [pantheon-agent-polkit](https://github.com/elementary/pantheon-agent-polkit). This is list of all files that it installed:
https://gist.github.com/LinArcX/8a90d0ab307269d697cee05cc58446bd

It's runing in the background:
`/usr/libexec/policykit-1-pantheon/io.elementary.desktop.agent-polkit`

**Comment by danrabbit** [comment]
@LinArcX the policy file being referenced is [here](https://github.com/elementary/switchboard-plug-useraccounts/blob/master/data/useraccounts.policy.in.in), it's not related to the polkit agent.

**Comment by LinArcX** [comment]
These are all files when i install `switchboard-plug-useraccounts`:
```
/usr/lib/switchboard/system/libuseraccounts.so
/usr/lib/switchboard/system/pantheon-useraccounts/guest-session-toggle
```
In which directory [this file](https://github.com/elementary/switchboard-plug-useraccounts/blob/master/data/useraccounts.policy.in.in) it'll be located?

**Comment by danrabbit** [comment]
@LinArcX It depends on where libpolkit defines it on your distro. See the build system here: https://github.com/elementary/switchboard-plug-useraccounts/blob/master/meson.build#L22

**Comment by LinArcX** [comment]
@danrabbit Thanks. Fixed! [by adding those two](https://github.com/void-linux/void-packages/pull/20617/files#diff-03e7be9e6cdf770fe5a8bf17109bea0aR18) files manually.
