### ISSUE TITLE
User avatar doesn't get updated 

### ISSUE THREAD

**Issue by CodeVault** [elementary/switchboard-plug-useraccounts#150]
## What Happened

User avatar does not update after changing it.

## Expected Behavior

New avatar instead of old one

## Steps to Reproduce

1. Open User Accounts in settings and simply change avatar.
2. Note: I have taken screen-shots but cant find any option here to upload one.

## Platform Information

eOS 6 daily builds

**Comment by danrabbit** [comment]
I can confirm that the sidebar updates, but the main view does not update when the avatar changes
