### ISSUE TITLE
Odin beta - Diacritics in account holder's name disappearing after each boot

### ISSUE THREAD

**Issue by WebShapedBiz** [elementary/switchboard-plug-useraccounts#167]
## What Happened
My account holder's name is "Siniša Perović". Not the username but my full name.
After reboot, the name gets changed to "Sinisa Perovic", without diacritics. I've changed it back, logged out, and the diacritic version persisted on Greeter and in the system after logging back in. However, after restart, the name has been changed back to "Sinisa Perovic", without diacritics.

I have a complete Croatian language setup, my keyboard is working fine, the interface is translated, time and date formats are correct and translated, I have no issue with the system-wide language setup.

## Expected Behavior
The system shouldn't remove diacritics from the account holder name

## Steps to Reproduce

1. Enter the account holder's full name using diacritics
2. Logout and log back in to see no change
3. Reboot and all diacritics from the account holder's name gets removed

## Platform Information
Version: elementary OS Odin Early Access (both beta1 and beta2 have this issue), vanilla version, nothing compiled or anything.

Cheers.

**Comment by vjr** [comment]
Where is the issue visible? Only on the greeter login screen or anywhere else?

**Comment by WebShapedBiz** [comment]
It is visible on

- Greeter login screen
- "Power" button on the Wingpanel (sorry, don't know the actual name of that button, is it a Session?)
- Switchboard -> User accounts

**Comment by vjr** [comment]
ok thank you for the clarification.

**Comment by vjr** [comment]
I couldn't reproduce the problem with my language/locale settings (US english, India region) or german either, don't see/know how to enable Croatia language/region.

@WebShapedBiz  what output do you get if you run the `locale` command in the terminal? Does the first item (`LANG=`) have a `.UTF-8` at the end of your output?

Oh well, I thought I might try and see if I could fix this if it were a minor issue but seems to be beyond my skillzzz.

**Comment by WebShapedBiz** [comment]
This is my `locale` output:
```
LANG=hr_HR.UTF-8
LANGUAGE=hr
LC_CTYPE="hr_HR.UTF-8"
LC_NUMERIC=hr_HR.UTF-8
LC_TIME=hr_HR.UTF-8
LC_COLLATE="hr_HR.UTF-8"
LC_MONETARY=hr_HR.UTF-8
LC_MESSAGES="hr_HR.UTF-8"
LC_PAPER=hr_HR.UTF-8
LC_NAME=hr_HR.UTF-8
LC_ADDRESS=hr_HR.UTF-8
LC_TELEPHONE=hr_HR.UTF-8
LC_MEASUREMENT=hr_HR.UTF-8
LC_IDENTIFICATION=hr_HR.UTF-8
LC_ALL=
```
Regardless of the outcome, thank you @vjr for your time and effort, I really appreciate it.

Cheers.

**Comment by meisenzahl** [comment]
Hey @WebShapedBiz could you please check `/etc/passwd` to see how your name is stored there?

You can read the content of the file like this:

`cat /etc/passwd`

There should be a line that looks like this:

`peter:1000:1000:Peter Parker,,:/home/peter:/bin/bash`

So in your case e.g.

`sinisa:1000:1000:Siniša Perović,,:/home/sinisa:/bin/bash`

or

`sinisa:1000:1000:Sinisa Perovic,,:/home/sinisa:/bin/bash`

Does the file contain the diacritics?

**Comment by WebShapedBiz** [comment]
Hi @meisenzahl.
`/etc/passwd` is correctly displaying diacritics but also, after several updates in the last few days, it seems that the problem is resolved :-)

Thank you for your time and effort though.

Cheers.
