### ISSUE TITLE
Missing Add User Option

### ISSUE THREAD

**Issue by Imauny** [elementary/switchboard-plug-useraccounts#236]
### What Happened?

The option to add a new user account to the PC is missing

### Steps to Reproduce

I went to settings under "User Acoounts" to try and add another user, but the option was missing.

### Expected Behavior

Should bea able to add a new user.

### OS Version

7.x (Horus)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
To add a new user you need to click the "+" icon at the bottom of the sidebar.  In OS8 this icon is supplemented by a "Create User Account ..." label to make it clearer.

**Comment by Imauny** [comment]
Thank you 😊

**Comment by danirabbit** [comment]
Closing as fixed since it sounds like this was resolved by a previous design change
