### ISSUE TITLE
[$25] Guest session shows 'Disabled' but active

### ISSUE THREAD

**Issue by Romdef** [elementary/switchboard-plug-useraccounts#24]
Since a recent update, in Users accounts, the guest session is marked as disabled.
But it's active.
I have to enable and disable, if I want to restore a normal usage : the guest session is marked as disabled and doesn't appear on the login screen.

**Comment by codygarver** [comment]
I created a bounty for this issue on [Bountysource](https://www.bountysource.com/issues/45692108-guest-session-shows-disabled-but-active).

**Comment by Romdef** [comment]
Thank you @codygarver !
